# GitHub Actions CI workflow template
#
# CUSTOMIZATION POINTS:
# - PYTHON_VERSION: Set to your required Python version
# - Secrets: Add any API keys needed for integration tests
# - Branches: Adjust branch patterns as needed

name: CI Tests

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.13"  # CUSTOMIZE: your Python version

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system ruff mypy

      - name: Run linting and static analysis
        run: make lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ env.PYTHON_VERSION }}-

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system -e ".[test]"

      - name: Run unit tests
        run: make test-unit

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unit
          name: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    # Only run on main, feature branches, or same-repo PRs (has secrets access)
    if: >
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/heads/feature/') ||
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --system -e ".[test]"

      - name: Run integration tests
        env:
          # CUSTOMIZE: Add your secrets here
          # API_KEY: ${{ secrets.API_KEY || 'dummy-key-for-mocks' }}
        run: make test-integration
        timeout-minutes: 10

  all-tests-passed:
    # Gate job to ensure all tests pass before merge
    needs: [lint, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check if all tests passed
        run: |
          if [[ "${{ needs.lint.result }}" != "success" || \
                "${{ needs.unit-tests.result }}" != "success" || \
                "${{ needs.integration-tests.result }}" != "success" ]]; then
            echo "One or more required tests failed"
            exit 1
          fi
          echo "All required tests passed!"
