version: '3.8'

services:
  # VictoriaLogs is managed separately, not part of this compose file
  # It's already running on port 9428
  
  # The loiter-killer service has been removed as vector store lifecycle
  # management is now integrated directly into the MCP server

networks:
  the-force-network:
    driver: bridge

volumes:
  the-force-logs-data:
    driver: local