[project]
name = "mcp_second_brain"
version = "0.3.2"
description = "Local MCP \"Second-Brain\" server with prompt-safe file inlining and vector-store attachments."
authors = [{name = "Your Name"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastmcp>=0.5.0",
    "openai>=1.62.0",
    "google-genai>=0.8.0",
    "tiktoken>=0.8.0",
    "lxml>=5.3.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0.0",
]

[project.scripts]
mcp-second-brain = "mcp_second_brain.server:main"
