#!/bin/bash
# RCT Spike Script: CLI Model Support Matrix
#
# This script tests which models are actually supported by each CLI.
# Run manually to validate assumptions about model support.
#
# IMPORTANT: This makes REAL API calls and costs money!
#
# Usage: ./scripts/rct/test_cli_model_support.sh [cli_name]
#   cli_name: claude, gemini, codex, or all (default: all)

set -e

# Test prompt - minimal to reduce cost
TEST_PROMPT="Reply with just the word 'ok'"

# Results file
RESULTS_FILE="scripts/rct/cli_model_support_results.md"

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_result() {
    local cli=$1
    local model=$2
    local status=$3
    local notes=$4

    if [ "$status" = "SUPPORTED" ]; then
        echo -e "${GREEN}✓${NC} $cli: $model - $status"
    else
        echo -e "${RED}✗${NC} $cli: $model - $status ($notes)"
    fi

    echo "| $cli | $model | $status | $notes |" >> "$RESULTS_FILE"
}

test_claude_model() {
    local model=$1
    echo "Testing Claude CLI with model: $model"

    # Use --print for JSON output, short prompt
    if output=$(claude --model "$model" --print -p "$TEST_PROMPT" 2>&1); then
        if echo "$output" | grep -q "ok\|OK"; then
            log_result "claude" "$model" "SUPPORTED" "Response received"
            return 0
        else
            log_result "claude" "$model" "SUPPORTED" "Response format differs"
            return 0
        fi
    else
        error=$(echo "$output" | head -1)
        log_result "claude" "$model" "NOT_SUPPORTED" "$error"
        return 1
    fi
}

test_gemini_model() {
    local model=$1
    echo "Testing Gemini CLI with model: $model"

    # Gemini CLI syntax
    if output=$(gemini --model "$model" "$TEST_PROMPT" 2>&1); then
        log_result "gemini" "$model" "SUPPORTED" "Response received"
        return 0
    else
        error=$(echo "$output" | head -1)
        log_result "gemini" "$model" "NOT_SUPPORTED" "$error"
        return 1
    fi
}

test_codex_model() {
    local model=$1
    echo "Testing Codex CLI with model: $model"

    # Codex uses exec for non-interactive, returns JSONL
    # Success = contains "thread.started" or "item.completed"
    # Failure = contains "error" or "invalid model"
    output=$(codex exec --model "$model" --json "$TEST_PROMPT" 2>&1) || true

    if echo "$output" | grep -q "thread.started\|item.completed"; then
        log_result "codex" "$model" "SUPPORTED" "Thread started successfully"
        return 0
    elif echo "$output" | grep -qi "error\|invalid\|not found"; then
        error=$(echo "$output" | grep -i "error\|invalid" | head -1)
        log_result "codex" "$model" "NOT_SUPPORTED" "$error"
        return 1
    else
        # Unknown response, assume supported if we got output
        log_result "codex" "$model" "SUPPORTED" "Response received"
        return 0
    fi
}

# Initialize results file
init_results() {
    cat > "$RESULTS_FILE" << 'EOF'
# CLI Model Support Matrix - RCT Results

Generated by: `scripts/rct/test_cli_model_support.sh`

## Results

| CLI | Model | Status | Notes |
|-----|-------|--------|-------|
EOF
}

test_claude_models() {
    echo -e "\n${YELLOW}=== Testing Claude CLI Models ===${NC}\n"

    # Anthropic models to test
    local models=(
        "claude-sonnet-4-5"
        "claude-opus-4-5-20251101"
        "claude-3-opus"
        "sonnet"  # alias
        "opus"    # alias
    )

    for model in "${models[@]}"; do
        test_claude_model "$model" || true
        sleep 1  # Rate limiting
    done
}

test_gemini_models() {
    echo -e "\n${YELLOW}=== Testing Gemini CLI Models ===${NC}\n"

    # Google models to test
    local models=(
        "gemini-3-pro-preview"
        "gemini-3-flash-preview"
        "gemini-2.5-flash"
        "gemini-2.5-pro"
    )

    for model in "${models[@]}"; do
        test_gemini_model "$model" || true
        sleep 1
    done
}

test_codex_models() {
    echo -e "\n${YELLOW}=== Testing Codex CLI Models ===${NC}\n"

    # OpenAI models to test
    local models=(
        "gpt-5.2"
        "gpt-5.2-pro"
        "gpt-4.1"
        "gpt-5.1-codex-max"
        "o3"
        "o4-mini"
    )

    for model in "${models[@]}"; do
        test_codex_model "$model" || true
        sleep 1
    done
}

main() {
    local target=${1:-all}

    echo "========================================"
    echo "RCT: CLI Model Support Matrix"
    echo "========================================"
    echo ""
    echo "WARNING: This makes real API calls!"
    echo ""

    init_results

    case $target in
        claude)
            test_claude_models
            ;;
        gemini)
            test_gemini_models
            ;;
        codex)
            test_codex_models
            ;;
        all)
            test_claude_models
            test_gemini_models
            test_codex_models
            ;;
        *)
            echo "Unknown CLI: $target"
            echo "Usage: $0 [claude|gemini|codex|all]"
            exit 1
            ;;
    esac

    echo ""
    echo "========================================"
    echo "Results saved to: $RESULTS_FILE"
    echo "========================================"
}

main "$@"
