name: E2E Tests

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual trigger
  push:
    branches:
      - main
      - feature/comprehensive-testing
    paths:
      - 'mcp_second_brain/**'
      - 'tests/e2e/**'
      - 'Dockerfile.e2e'
      - '.github/workflows/e2e.yml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build E2E test image
      run: docker build -f Dockerfile.e2e -t mcp-e2e:latest .
    
    - name: Set up Google Cloud credentials
      if: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON != '' }}
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > /tmp/gcloud-key.json
    
    - name: Run E2E tests
      env:
        CI_E2E: "1"
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        VERTEX_PROJECT: ${{ secrets.VERTEX_PROJECT }}
        VERTEX_LOCATION: ${{ secrets.VERTEX_LOCATION }}
      run: |
        # Set up Docker run command
        DOCKER_CMD="docker run --rm"
        DOCKER_CMD="$DOCKER_CMD -e CI_E2E"
        DOCKER_CMD="$DOCKER_CMD -e OPENAI_API_KEY"
        DOCKER_CMD="$DOCKER_CMD -e ANTHROPIC_API_KEY"
        DOCKER_CMD="$DOCKER_CMD -e VERTEX_PROJECT"
        DOCKER_CMD="$DOCKER_CMD -e VERTEX_LOCATION"
        
        # Add Google credentials if available
        if [ -f /tmp/gcloud-key.json ]; then
          DOCKER_CMD="$DOCKER_CMD -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud/key.json"
          DOCKER_CMD="$DOCKER_CMD -v /tmp/gcloud-key.json:/tmp/gcloud/key.json:ro"
        fi
        
        # Run tests
        $DOCKER_CMD mcp-e2e:latest pytest tests/e2e -v --tb=short
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-results
        path: |
          **/pytest_report.xml
          **/mcp-second-brain-debug.log